# Reading data from SQL

# 1. PostgreSQL

In [8]:
import pandas as pd
import sqlalchemy

In [49]:
conn = sqlalchemy.create_engine('postgresql+psycopg2://postgres:airflow@localhost:5432/data_wrangling')

## Read SQL DB Table

In [4]:
pd.read_sql_table('citibike', conn)

,tripduration,starttime,stoptime,start_station_id,start_station_name,start_station_latitude,start_station_longitude,end_station_id,end_station_name,end_station_latitude,end_station_longitude,bikeid,usertype,birth_year,gender
0,320,2019-01-01 00:01:47.401,2019-01-01 00:07:07.581,3160.0,Central Park West & W 76 St,40.778968,-73.973747,3283.0,W 89 St & Columbus Ave,40.788221,-73.970416,15839,Subscriber,1971,1
1,316,2019-01-01 00:04:43.736,2019-01-01 00:10:00.608,519.0,Pershing Square North,40.751873,-73.977706,518.0,E 39 St & 2 Ave,40.747804,-73.973442,32723,Subscriber,1964,1
2,591,2019-01-01 00:06:03.997,2019-01-01 00:15:55.438,3171.0,Amsterdam Ave & W 82 St,40.785247,-73.976673,3154.0,E 77 St & 3 Ave,40.773142,-73.958562,27451,Subscriber,1987,1
3,2719,2019-01-01 00:07:03.545,2019-01-01 00:52:22.650,504.0,1 Ave & E 16 St,40.732219,-73.981656,3709.0,W 15 St & 6 Ave,40.738046,-73.996430,21579,Subscriber,1990,1
4,303,2019-01-01 00:07:35.945,2019-01-01 00:12:39.502,229.0,Great Jones St,40.727434,-73.993790,503.0,E 20 St & Park Ave,40.738274,-73.987520,35379,Subscriber,1979,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
967282,291,2019-01-31 17:33:26.449,2019-01-31 17:38:17.894,3354.0,3 St & Prospect Park West,40.668132,-73.973638,3423.0,West Drive & Prospect Park West,40.661063,-73.979453,19780,Subscriber,1978,2
967283,437,2019-01-31 18:57:45.338,2019-01-31 19:05:02.497,3354.0,3 St & Prospect Park West,40.668132,-73.973638,3313.0,6 Ave & 12 St,40.666318,-73.985462,34365,Subscriber,1976,2
967284,173,2019-01-31 19:11:41.193,2019-01-31 19:14:34.335,3354.0,3 St & Prospect Park West,40.668132,-73.973638,3418.0,Plaza St West & Flatbush Ave,40.675021,-73.971115,25889,Subscriber,1977,1
967285,244,2019-01-31 20:54:51.144,2019-01-31 20:58:55.310,3354.0,3 St & Prospect Park West,40.668132,-73.973638,3346.0,Berkeley Pl & 7 Ave,40.675147,-73.975232,34649,Subscriber,1994,1
967286,387,2019-01-31 23:38:42.177,2019-01-31 23:45:09.452,3354.0,3 St & Prospect Park West,40.668132,-73.973638,3549.0,Grand Ave & Bergen St,40.678045,-73.962408,17299,Subscriber,1979,1

## Read SQL Database using query

In [4]:
pd.read_sql_query('select * from citibike', conn)

,tripduration,starttime,stoptime,start_station_id,start_station_name,start_station_latitude,start_station_longitude,end_station_id,end_station_name,end_station_latitude,end_station_longitude,bikeid,usertype,birth_year,gender
0,320,2019-01-01 00:01:47.401,2019-01-01 00:07:07.581,3160.0,Central Park West & W 76 St,40.778968,-73.973747,3283.0,W 89 St & Columbus Ave,40.788221,-73.970416,15839,Subscriber,1971,1
1,316,2019-01-01 00:04:43.736,2019-01-01 00:10:00.608,519.0,Pershing Square North,40.751873,-73.977706,518.0,E 39 St & 2 Ave,40.747804,-73.973442,32723,Subscriber,1964,1
2,591,2019-01-01 00:06:03.997,2019-01-01 00:15:55.438,3171.0,Amsterdam Ave & W 82 St,40.785247,-73.976673,3154.0,E 77 St & 3 Ave,40.773142,-73.958562,27451,Subscriber,1987,1
3,2719,2019-01-01 00:07:03.545,2019-01-01 00:52:22.650,504.0,1 Ave & E 16 St,40.732219,-73.981656,3709.0,W 15 St & 6 Ave,40.738046,-73.996430,21579,Subscriber,1990,1
4,303,2019-01-01 00:07:35.945,2019-01-01 00:12:39.502,229.0,Great Jones St,40.727434,-73.993790,503.0,E 20 St & Park Ave,40.738274,-73.987520,35379,Subscriber,1979,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
967282,291,2019-01-31 17:33:26.449,2019-01-31 17:38:17.894,3354.0,3 St & Prospect Park West,40.668132,-73.973638,3423.0,West Drive & Prospect Park West,40.661063,-73.979453,19780,Subscriber,1978,2
967283,437,2019-01-31 18:57:45.338,2019-01-31 19:05:02.497,3354.0,3 St & Prospect Park West,40.668132,-73.973638,3313.0,6 Ave & 12 St,40.666318,-73.985462,34365,Subscriber,1976,2
967284,173,2019-01-31 19:11:41.193,2019-01-31 19:14:34.335,3354.0,3 St & Prospect Park West,40.668132,-73.973638,3418.0,Plaza St West & Flatbush Ave,40.675021,-73.971115,25889,Subscriber,1977,1
967285,244,2019-01-31 20:54:51.144,2019-01-31 20:58:55.310,3354.0,3 St & Prospect Park West,40.668132,-73.973638,3346.0,Berkeley Pl & 7 Ave,40.675147,-73.975232,34649,Subscriber,1994,1
967286,387,2019-01-31 23:38:42.177,2019-01-31 23:45:09.452,3354.0,3 St & Prospect Park West,40.668132,-73.973638,3549.0,Grand Ave & Bergen St,40.678045,-73.962408,17299,Subscriber,1979,1

## Do both with only ONE API

In [5]:
pd.read_sql('citibike', conn)

,tripduration,starttime,stoptime,start_station_id,start_station_name,start_station_latitude,start_station_longitude,end_station_id,end_station_name,end_station_latitude,end_station_longitude,bikeid,usertype,birth_year,gender
0,320,2019-01-01 00:01:47.401,2019-01-01 00:07:07.581,3160.0,Central Park West & W 76 St,40.778968,-73.973747,3283.0,W 89 St & Columbus Ave,40.788221,-73.970416,15839,Subscriber,1971,1
1,316,2019-01-01 00:04:43.736,2019-01-01 00:10:00.608,519.0,Pershing Square North,40.751873,-73.977706,518.0,E 39 St & 2 Ave,40.747804,-73.973442,32723,Subscriber,1964,1
2,591,2019-01-01 00:06:03.997,2019-01-01 00:15:55.438,3171.0,Amsterdam Ave & W 82 St,40.785247,-73.976673,3154.0,E 77 St & 3 Ave,40.773142,-73.958562,27451,Subscriber,1987,1
3,2719,2019-01-01 00:07:03.545,2019-01-01 00:52:22.650,504.0,1 Ave & E 16 St,40.732219,-73.981656,3709.0,W 15 St & 6 Ave,40.738046,-73.996430,21579,Subscriber,1990,1
4,303,2019-01-01 00:07:35.945,2019-01-01 00:12:39.502,229.0,Great Jones St,40.727434,-73.993790,503.0,E 20 St & Park Ave,40.738274,-73.987520,35379,Subscriber,1979,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
967282,291,2019-01-31 17:33:26.449,2019-01-31 17:38:17.894,3354.0,3 St & Prospect Park West,40.668132,-73.973638,3423.0,West Drive & Prospect Park West,40.661063,-73.979453,19780,Subscriber,1978,2
967283,437,2019-01-31 18:57:45.338,2019-01-31 19:05:02.497,3354.0,3 St & Prospect Park West,40.668132,-73.973638,3313.0,6 Ave & 12 St,40.666318,-73.985462,34365,Subscriber,1976,2
967284,173,2019-01-31 19:11:41.193,2019-01-31 19:14:34.335,3354.0,3 St & Prospect Park West,40.668132,-73.973638,3418.0,Plaza St West & Flatbush Ave,40.675021,-73.971115,25889,Subscriber,1977,1
967285,244,2019-01-31 20:54:51.144,2019-01-31 20:58:55.310,3354.0,3 St & Prospect Park West,40.668132,-73.973638,3346.0,Berkeley Pl & 7 Ave,40.675147,-73.975232,34649,Subscriber,1994,1
967286,387,2019-01-31 23:38:42.177,2019-01-31 23:45:09.452,3354.0,3 St & Prospect Park West,40.668132,-73.973638,3549.0,Grand Ave & Bergen St,40.678045,-73.962408,17299,Subscriber,1979,1

In [46]:
pd.read_sql('select * from citibike', conn)

,tripduration,starttime,stoptime,start_station_id,start_station_name,start_station_latitude,start_station_longitude,end_station_id,end_station_name,end_station_latitude,end_station_longitude,bikeid,usertype,birth_year,gender
0,320,2019-01-01 00:01:47.401,2019-01-01 00:07:07.581,3160.0,Central Park West & W 76 St,40.778968,-73.973747,3283.0,W 89 St & Columbus Ave,40.788221,-73.970416,15839,Subscriber,1971,1
1,316,2019-01-01 00:04:43.736,2019-01-01 00:10:00.608,519.0,Pershing Square North,40.751873,-73.977706,518.0,E 39 St & 2 Ave,40.747804,-73.973442,32723,Subscriber,1964,1
2,591,2019-01-01 00:06:03.997,2019-01-01 00:15:55.438,3171.0,Amsterdam Ave & W 82 St,40.785247,-73.976673,3154.0,E 77 St & 3 Ave,40.773142,-73.958562,27451,Subscriber,1987,1
3,2719,2019-01-01 00:07:03.545,2019-01-01 00:52:22.650,504.0,1 Ave & E 16 St,40.732219,-73.981656,3709.0,W 15 St & 6 Ave,40.738046,-73.996430,21579,Subscriber,1990,1
4,303,2019-01-01 00:07:35.945,2019-01-01 00:12:39.502,229.0,Great Jones St,40.727434,-73.993790,503.0,E 20 St & Park Ave,40.738274,-73.987520,35379,Subscriber,1979,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
967282,291,2019-01-31 17:33:26.449,2019-01-31 17:38:17.894,3354.0,3 St & Prospect Park West,40.668132,-73.973638,3423.0,West Drive & Prospect Park West,40.661063,-73.979453,19780,Subscriber,1978,2
967283,437,2019-01-31 18:57:45.338,2019-01-31 19:05:02.497,3354.0,3 St & Prospect Park West,40.668132,-73.973638,3313.0,6 Ave & 12 St,40.666318,-73.985462,34365,Subscriber,1976,2
967284,173,2019-01-31 19:11:41.193,2019-01-31 19:14:34.335,3354.0,3 St & Prospect Park West,40.668132,-73.973638,3418.0,Plaza St West & Flatbush Ave,40.675021,-73.971115,25889,Subscriber,1977,1
967285,244,2019-01-31 20:54:51.144,2019-01-31 20:58:55.310,3354.0,3 St & Prospect Park West,40.668132,-73.973638,3346.0,Berkeley Pl & 7 Ave,40.675147,-73.975232,34649,Subscriber,1994,1
967286,387,2019-01-31 23:38:42.177,2019-01-31 23:45:09.452,3354.0,3 St & Prospect Park West,40.668132,-73.973638,3549.0,Grand Ave & Bergen St,40.678045,-73.962408,17299,Subscriber,1979,1

## Increase Performance of reading data from Postgresql using Asyncronous method

In [2]:
import asyncpg
import asyncio
from datetime import datetime
import nest_asyncio

In [3]:
nest_asyncio.apply()

In [23]:
async_conn = await asyncpg.connect(host='localhost', port='5432', user='postgres', password='airflow', database='data_wrangling')

In [21]:
rows = await async_conn.fetch('select * from citibike')
df = pd.DataFrame(rows, columns=[i for i in rows[0].keys()])

!uv add nest_asyncio

## Small table performance comparison

In [25]:
async def run_query():
    return await async_conn.fetch('select * from citibike')

# Now you can use a synchronous wrapper with %timeit
def sync_wrapper():
    return asyncio.get_event_loop().run_until_complete(run_query())

In [26]:
%%timeit 
sync_wrapper()

9.55 s ± 130 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [27]:
con = conn.raw_connection()

In [28]:
%%timeit
with con.cursor() as cur:
    cur.execute("select * from citibike;")
    records = cur.fetchall()

12.9 s ± 1.97 s per loop (mean ± std. dev. of 7 runs, 1 loop each)

## Large table performance comparison

In [29]:
async def run_query():
    return await async_conn.fetch('select * from "2019_citibike"')

# Now you can use a synchronous wrapper with %timeit
def sync_wrapper():
    return asyncio.get_event_loop().run_until_complete(run_query())

In [30]:
%%timeit 
sync_wrapper()

2min 20s ± 7.52 s per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [31]:
%%timeit
with con.cursor() as cur:
    cur.execute('select * from "2019_citibike"')
    records = cur.fetchall()

4min 13s ± 17.9 s per loop (mean ± std. dev. of 7 runs, 1 loop each)

# 2. Other Databases

## For synchronous connection with SQLAlchemy, the differences are only:
* Connection string
* SQL Dialague

!uv add mysql-connector-python

In [3]:
my_conn = sqlalchemy.create_engine('mysql+pymysql://root:airflow@localhost/data_wrangling')

In [5]:
my_raw_conn = my_conn.raw_connection()

In [6]:
%%timeit
with my_raw_conn.cursor() as cur:
    cur.execute("select * from citibike_2019 where starttime like '2019-01%'")
    records = cur.fetchall()

1min 47s ± 6.07 s per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [8]:
!uv add aiomysql

Resolved 122 packages in 3.26s
warning: `numpy==2.4.0` is yanked (reason: "Backward compatibility bug")
warning: `numpy==2.4.0` is yanked (reason: "Backward compatibility bug")
Prepared 1 package in 745ms
Installed 1 package in 150ms
 + aiomysql==0.3.2

In [12]:
import asyncio
import aiomysql

In [20]:
async def async_mysql():
    async with aiomysql.create_pool(host='127.0.0.1', port=3306,
                                    user='root', password='airflow',
                                    db='data_wrangling') as pool:
        async with pool.acquire() as conn:
            async with conn.cursor() as cur:
                await cur.execute("select * from citibike_2019 where starttime like '2019-01%'")
                records = await cur.fetchall()

In [21]:
def sync_wrapper():
    return asyncio.get_event_loop().run_until_complete(async_mysql())

In [22]:
%%timeit
sync_wrapper()

1min 37s ± 7.5 s per loop (mean ± std. dev. of 7 runs, 1 loop each)

# Do GDT App and Website use Google Analytics? If YES, let's walk through how to read app/web

In [27]:
!uv add pandas-gbq

^C

Resolved 143 packages in 3m 21s
warning: `numpy==2.4.0` is yanked (reason: "Backward compatibility bug")
warning: `numpy==2.4.0` is yanked (reason: "Backward compatibility bug")
Prepared 21 packages in 23.75s
Installed 21 packages in 1.52s
 + cryptography==46.0.4
 + db-dtypes==1.5.0
 + google-api-core==2.29.0
 + google-auth==2.48.0
 + google-auth-oauthlib==1.2.4
 + google-cloud-bigquery==3.40.0
 + google-cloud-core==2.5.0
 + google-crc32c==1.8.0
 + google-resumable-media==2.8.0
 + googleapis-common-protos==1.72.0
 + grpcio==1.76.0
 + grpcio-status==1.76.0
 + oauthlib==3.3.1
 + pandas-gbq==0.33.0
 + proto-plus==1.27.0
 + protobuf==6.33.4
 + pyasn1==0.6.2
 + pyasn1-modules==0.4.2
 + pydata-google-auth==1.9.1
 + requests-oauthlib==2.0.0
 + rsa==4.9.1

In [1]:
import os
import pandas_gbq

In [2]:
os.environ['GOOGLE_APPLICATION_CREDENTIALS']='creds/analytics-training-485714-ccd6a252ff9d.json'

In [5]:
G_QUERY = """
SELECT
  *
FROM `bigquery-public-data.ga4_obfuscated_sample_ecommerce.events_20210131`
"""

## Read all at once (convenient)

In [15]:
%%timeit
df = pandas_gbq.read_gbq(G_QUERY, project_id='analytics-training-485714')

C:\Users\admin\Documents\gdt_training\python_for_data_wrangling\py_projs\.venv\Lib\site-packages\google\cloud\bigquery\table.py:2689: UserWarning: A progress bar was requested, but there was an error loading the tqdm library. Please install tqdm to use the progress bar functionality.
  record_batch = self.to_arrow(
C:\Users\admin\Documents\gdt_training\python_for_data_wrangling\py_projs\.venv\Lib\site-packages\google\cloud\bigquery\table.py:2689: UserWarning: A progress bar was requested, but there was an error loading the tqdm library. Please install tqdm to use the progress bar functionality.
  record_batch = self.to_arrow(
C:\Users\admin\Documents\gdt_training\python_for_data_wrangling\py_projs\.venv\Lib\site-packages\google\cloud\bigquery\table.py:2689: UserWarning: A progress bar was requested, but there was an error loading the tqdm library. Please install tqdm to use the progress bar functionality.
  record_batch = self.to_arrow(
C:\Users\admin\Documents\gdt_training\python_for_data_wrangling\py_projs\.venv\Lib\site-packages\google\cloud\bigquery\table.py:2689: UserWarning: A progress bar was requested, but there was an error loading the tqdm library. Please install tqdm to use the progress bar functionality.
  record_batch = self.to_arrow(
C:\Users\admin\Documents\gdt_training\python_for_data_wrangling\py_projs\.venv\Lib\site-packages\google\cloud\bigquery\table.py:2689: UserWarning: A progress bar was requested, but there was an error loading the tqdm library. Please install tqdm to use the progress bar functionality.
  record_batch = self.to_arrow(
C:\Users\admin\Documents\gdt_training\python_for_data_wrangling\py_projs\.venv\Lib\site-packages\google\cloud\bigquery\table.py:2689: UserWarning: A progress bar was requested, but there was an error loading the tqdm library. Please install tqdm to use the progress bar functionality.
  record_batch = self.to_arrow(
C:\Users\admin\Documents\gdt_training\python_for_data_wrangling\py_projs\.venv\Lib\site-packages\google\cloud\bigquery\table.py:2689: UserWarning: A progress bar was requested, but there was an error loading the tqdm library. Please install tqdm to use the progress bar functionality.
  record_batch = self.to_arrow(
C:\Users\admin\Documents\gdt_training\python_for_data_wrangling\py_projs\.venv\Lib\site-packages\google\cloud\bigquery\table.py:2689: UserWarning: A progress bar was requested, but there was an error loading the tqdm library. Please install tqdm to use the progress bar functionality.
  record_batch = self.to_arrow(

53.8 s ± 761 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

## Read chunk by chunk using row iterators and process it (more scalable)

!uv add google-cloud-bigquery

In [3]:
from google.cloud import bigquery
client = bigquery.Client()

In [14]:
%%timeit
query_job = client.query(G_QUERY)
rows = query_job.result()  
ls = []
for row in rows:
    ls.append(row)

51 s ± 1.13 s per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [12]:
type(rows)

google.cloud.bigquery.table.RowIterator

In [27]:
list(ls[0].keys())

['event_date',
 'event_timestamp',
 'event_name',
 'event_params',
 'event_previous_timestamp',
 'event_value_in_usd',
 'event_bundle_sequence_id',
 'event_server_timestamp_offset',
 'user_id',
 'user_pseudo_id',
 'privacy_info',
 'user_properties',
 'user_first_touch_timestamp',
 'user_ltv',
 'device',
 'geo',
 'app_info',
 'traffic_source',
 'stream_id',
 'platform',
 'event_dimensions',
 'ecommerce',
 'items']

In [19]:
ls[0].values()

('20210131',
 1612069510766593,
 'page_view',
 [{'key': 'gclid',
   'value': {'string_value': None,
    'int_value': None,
    'float_value': None,
    'double_value': None}},
  {'key': 'gclsrc',
   'value': {'string_value': None,
    'int_value': None,
    'float_value': None,
    'double_value': None}},
  {'key': 'debug_mode',
   'value': {'string_value': None,
    'int_value': 1,
    'float_value': None,
    'double_value': None}},
  {'key': 'ga_session_number',
   'value': {'string_value': None,
    'int_value': 1,
    'float_value': None,
    'double_value': None}},
  {'key': 'all_data',
   'value': {'string_value': None,
    'int_value': None,
    'float_value': None,
    'double_value': None}},
  {'key': 'page_location',
   'value': {'string_value': 'https://shop.googlemerchandisestore.com/',
    'int_value': None,
    'float_value': None,
    'double_value': None}},
  {'key': 'entrances',
   'value': {'string_value': None,
    'int_value': 1,
    'float_value': None,
    'double_value': None}},
  {'key': 'session_engaged',
   'value': {'string_value': '0',
    'int_value': None,
    'float_value': None,
    'double_value': None}},
  {'key': 'ga_session_id',
   'value': {'string_value': None,
    'int_value': 661084800,
    'float_value': None,
    'double_value': None}},
  {'key': 'clean_event',
   'value': {'string_value': 'gtm.js',
    'int_value': None,
    'float_value': None,
    'double_value': None}},
  {'key': 'engaged_session_event',
   'value': {'string_value': None,
    'int_value': 1,
    'float_value': None,
    'double_value': None}},
  {'key': 'page_title',
   'value': {'string_value': 'Home',
    'int_value': None,
    'float_value': None,
    'double_value': None}}],
 None,
 None,
 6595101026,
 None,
 None,
 '1026454.4271112504',
 {'analytics_storage': None,
  'ads_storage': None,
  'uses_transient_token': 'No'},
 [],
 1612069510766593,
 {'revenue': 0.0, 'currency': 'USD'},
 {'category': 'mobile',
  'mobile_brand_name': 'Apple',
  'mobile_model_name': 'iPhone',
  'mobile_marketing_name': '<Other>',
  'mobile_os_hardware_model': None,
  'operating_system': 'Web',
  'operating_system_version': '<Other>',
  'vendor_id': None,
  'advertising_id': None,
  'language': 'en-us',
  'is_limited_ad_tracking': 'No',
  'time_zone_offset_seconds': None,
  'web_info': {'browser': 'Safari', 'browser_version': '13.1'}},
 {'continent': 'Americas',
  'sub_continent': 'Northern America',
  'country': 'United States',
  'region': 'California',
  'city': 'San Carlos',
  'metro': '(not set)'},
 None,
 {'medium': 'organic', 'name': '(organic)', 'source': 'google'},
 2100450278,
 'WEB',
 None,
 {'total_item_quantity': None,
  'purchase_revenue_in_usd': None,
  'purchase_revenue': None,
  'refund_value_in_usd': None,
  'refund_value': None,
  'shipping_value_in_usd': None,
  'shipping_value': None,
  'tax_value_in_usd': None,
  'tax_value': None,
  'unique_items': None,
  'transaction_id': None},
 [])